In [ ]:
#pip install plotly==5.24.1 --upgrade

In [1]:
import plotly
print(plotly.__version__)

5.24.1

In [2]:
import pandas as pd
import plotly.express as px

df_1996_2024 = pd.read_csv('data_small_100.csv')
df_1996_2024

,Id,DateTime,Species,Group-Size,Lat,Long,Year,sst,Distance,Depth
0,7352,2010-08-06,Bryde´s Whale,2.0,28.018000,-17.296167,2010,22.370403,2316.0,355.0
1,7139,2010-04-06,Atlantic Spotted Dolphin,80.0,28.017833,-17.375167,2010,20.117405,7115.0,1284.0
2,4991,2006-10-19,Short-finned Pilot Whale,30.0,27.956667,-17.223500,2006,24.100436,7264.0,1652.0
3,6109,2008-09-29,Atlantic Spotted Dolphin,10.0,27.996000,-17.367500,2008,24.003021,8410.0,1476.0
4,10716,2016-02-10,Rough-toothed Dolphin,5.0,28.037000,-17.382500,2016,20.344462,6688.0,899.0
...,...,...,...,...,...,...,...,...,...,...
95,N907,2024-01-17,Short-finned Pilot Whale,22.0,27.962567,-17.241215,2024,21.405774,6342.0,1057.0
96,5008,2006-10-27,Atlantic Spotted Dolphin,50.0,28.005667,-17.337333,2006,23.795007,5804.0,1014.0
97,11861,2017-07-19,Bottlenose Dolphin,40.0,28.049000,-17.389833,2017,23.154118,6447.0,726.0
98,4987,2006-10-17,Bottlenose Dolphin,18.0,27.987167,-17.324167,2006,23.963469,6595.0,1288.0
99,6988,2010-01-16,Short-finned Pilot Whale,100.0,28.013167,-17.370000,2010,20.859371,7090.0,1299.0

In [ ]:
import pandas as pd
import plotly.express as px

df = df_1996_2024.copy()
fig = px.density_map(df, lat='Lat', lon='Long', radius=10,
                        center=dict(lat=df.Lat.mean(), lon=df.Long.mean()), zoom=10,
                        map_style="open-street-map")
fig.update_layout(width=1200, height=800)
fig.show()

In [ ]:
df_1996_2024.describe()

,Group-Size,Lat,Long,Year,sst,Distance,Depth
count,95.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,37.452632,28.011093,-17.330968,2011.490000,21.686740,5460.240000,917.840000
std,70.200286,0.033359,0.042656,6.161947,1.865816,2427.169966,525.843425
min,0.000000,27.953000,-17.418000,1998.000000,18.295816,278.000000,22.000000
25%,7.000000,27.990750,-17.358708,2006.000000,20.322123,4291.000000,459.250000
50%,18.000000,28.009583,-17.334750,2011.000000,21.294443,5860.500000,1059.500000
75%,32.500000,28.029750,-17.304708,2016.000000,23.211982,6840.500000,1265.250000
max,500.000000,28.174167,-17.176833,2024.000000,26.206946,11693.000000,2099.000000

[Plotly : scatter_map](https://plotly.com/python-api-reference/generated/plotly.express.scatter_map.html)

In [ ]:
df = df_1996_2024.copy().sample(n=50)
df2 = df_1996_2024.copy().sample(n=50)
fig_base = px.scatter_map(df, lat='Lat', lon='Long',
                        center=dict(lat=df.Lat.mean(), lon=df.Long.mean()), zoom=10,
                        map_style="open-street-map",hover_name="Species", hover_data=['Depth','Distance','Group-Size'],labels={'Lat':'Latitude'})

fig_base.update_traces(marker=dict(size=6, color="red", symbol="circle"))

fig_added = px.scatter_map(df2, lat='Lat', lon='Long',
                        center=dict(lat=df.Lat.mean(), lon=df.Long.mean()), zoom=10,
                        map_style="open-street-map",hover_name="Species", hover_data=['Depth','Distance','Group-Size'],labels={'Lat':'Latitude'})

fig_added.update_traces(marker=dict(size=6, color="blue", symbol="circle"))

# Add scatter traces to fig_base
for trace in fig_added.data:
    fig_base.add_trace(trace)

fig_base.update_layout(width=1200, height=800)
fig_base.show()

In [ ]:
df1 = df_1996_2024.copy().sample(n=100)
#df2 = df_1996_2024.copy().sample(n=50)
#df3 = df_1996_2024.copy().sample(n=50)

#combined_df = pd.concat([df1, df2, df3])
combined_df = df1

fig = px.scatter_map(
    combined_df,
    lat='Lat',
    lon='Long',
    color="Species",
    zoom=10,
    map_style="open-street-map",
    hover_data=['Id','Depth','Distance','Group-Size']
)

fig.update_layout(width=1200, height=800)
fig.show()